"use client";
import {useMemo,useState} from "react";import Link from "next/link";import Image from "next/image";import {Search,ShieldCheck,ArrowRight,Globe2} from "lucide-react";import {foods,pets,PetKey,statusCopy} from "@/lib/pet-data";
export default function PetNyamHome({lang="ko"}:{lang?:"ko"|"en"}){const[pet,setPet]=useState<PetKey>("dog");const[q,setQ]=useState("");const list=useMemo(()=>foods.filter(f=>(f.ko+f.en+f.aliases.join(" ")).toLowerCase().includes(q.toLowerCase())).slice(0,6),[q]);const ko=lang==="ko";return <main>
<header className="topbar"><Link className="brand" href={ko?"/":"/en"}><span className="brand-mark">P</span><span>PetNyam<small>펫냠</small></span></Link><nav><a href="#popular">{ko?"인기 음식":"Popular"}</a><a href="#trust">{ko?"검증 원칙":"Method"}</a><Link className="lang" href={ko?"/en":"/"}><Globe2 size={17}/>{ko?"EN":"한국어"}</Link></nav></header>
<section className="hero"><div className="hero-copy"><div className="eyebrow"><ShieldCheck size={17}/>{ko?"검증된 데이터베이스 기반":"Verified database, not instant AI"}</div><h1>{ko?<>우리 아이, <em>이 음식</em><br/>먹어도 될까?</>:<>Can my pet eat<br/><em>this food?</em></>}</h1><p>{ko?"반려동물을 고르고 음식을 검색하세요. 핵심 주의사항과 확인한 근거를 한눈에 알려드려요.":"Choose your pet and search a food. See the verdict, key cautions and reviewed sources at a glance."}</p><div className="finder"><label>{ko?"먼저 반려동물을 골라주세요":"Choose your pet"}</label><div className="pet-row">{(Object.keys(pets) as PetKey[]).map(k=><button key={k} className={pet===k?"active":""} onClick={()=>setPet(k)}><span>{pets[k].emoji}</span>{ko?pets[k].ko:pets[k].en}</button>)}</div><div className="searchbox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ko?"음식을 검색해보세요 (예: 사과)":"Search a food (e.g. apple)"}/></div>{q&&<div className="suggestions">{list.length?list.map(f=><Link key={f.slug} href={`/${lang}/${pet}/${f.slug}`}><span>{f.emoji} {ko?f.ko:f.en}</span><b style={{color:statusCopy[f.results[pet]].color}}>{ko?statusCopy[f.results[pet]].shortKo:statusCopy[f.results[pet]].en}<ArrowRight size={16}/></b></Link>):<p>{ko?"검색 결과가 없어요. V1 데이터에 곧 추가할게요.":"No match in the V1 database yet."}</p>}</div>}</div></div><div className="hero-visual"><Image src="/petnyam-hero.png" alt="PetNyam companion animals" fill priority sizes="(max-width:800px) 100vw,50vw"/></div></section>
<section className="quick"><div><strong>4</strong><span>{ko?"단계 안전 판정":"verdict levels"}</span></div><div><strong>10</strong><span>{ko?"V1 인기 음식":"popular V1 foods"}</span></div><div><strong>2+</strong><span>{ko?"교차 확인 출처":"review sources"}</span></div><div><strong>2026.09</strong><span>{ko?"최종 검토":"last reviewed"}</span></div></section>
<section id="popular" className="section"><div className="section-head"><div><p>{ko?"많이 찾는 질문":"TRENDING QUESTIONS"}</p><h2>{ko?`${pets[pet].ko} 보호자가 자주 찾는 음식`:`Popular foods for ${pets[pet].en.toLowerCase()} owners`}</h2></div><span>{ko?"반려동물을 바꾸면 판정도 달라져요":"Verdicts change by animal"}</span></div><div className="food-grid">{foods.slice(0,8).map(f=>{const s=statusCopy[f.results[pet]];return <Link key={f.slug} href={`/${lang}/${pet}/${f.slug}`} className="food-card"><span className="food-emoji">{f.emoji}</span><div><h3>{ko?f.ko:f.en}</h3><p>{f.en}</p></div><b style={{color:s.color,background:s.bg}}>{ko?s.shortKo:s.en}</b><ArrowRight className="arr"/></Link>})}</div></section>
<section id="trust" className="trust"><div><span className="trust-icon"><ShieldCheck/></span><p>{ko?"PetNyam의 약속":"OUR PROMISE"}</p><h2>{ko?"모르는 건, 모른다고 말합니다.":"When evidence is unclear, we say so."}</h2></div><p>{ko?"PetNyam은 AI가 즉석에서 안전성을 추측하지 않습니다. 수의학·동물복지 기관의 공개 자료를 검토해 구조화한 데이터만 보여주며, 근거가 충분하지 않으면 ‘정보부족’으로 남깁니다.":"PetNyam does not ask AI to guess food safety. It displays structured records reviewed against veterinary and animal-welfare sources, and marks insufficient evidence as unknown."}</p></section><div className="ad-slot"><span>ADVERTISEMENT</span><p>{ko?"콘텐츠 흐름을 방해하지 않는 광고 영역":"Reserved ad space"}</p></div>
<footer><div className="brand"><span className="brand-mark">P</span><span>PetNyam<small>펫냠</small></span></div><p>{ko?"반려동물 음식 안전 정보를 더 빠르고 분명하게.":"Clearer food-safety information for pet families."}</p><div><Link href="/policy/terms">{ko?"이용약관":"Terms"}</Link><Link href="/policy/privacy">{ko?"개인정보처리방침":"Privacy"}</Link><Link href="/policy/disclaimer">{ko?"의학적 면책":"Disclaimer"}</Link></div><small>© 2026 PetNyam. 본 서비스는 수의사의 진료를 대신하지 않습니다.</small></footer></main>}
